name: CI-CD Pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List repo files (Debug)
      run: ls -R

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build JAR
      run: mvn -f Spring_boot_CRUD-main/learningSpringBoot/pom.xml clean package -DskipTests

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app ./Spring_boot_CRUD-main/learningSpringBoot

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: springboot-service
        region: asia-south1
        project_id: divine-quest-459017-j2
        image: docker.io/${{ secrets.DOCKER_USERNAME }}/springboot-app





























# name: CI-CD Pipeline
# on:
#   push:
#     branches: [ "main" ]
# jobs:
#   build-push-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: List repo files (Debug)
#       run: ls -R

#     - name: Set up Java 17
#       uses: actions/setup-java@v4
#       with:
#         distribution: 'temurin'
#         java-version: '17'

#     - name: Build JAR
#       run: mvn -f Spring_boot_CRUD-main/learningSpringBoot/pom.xml clean package -DskipTests

#     - name: Login to Docker Hub
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#     - name: Build Docker image
#       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app ./Spring_boot_CRUD-main/learningSpringBoot

#     - name: Push Docker image
#       run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app

#     - name: Authenticate to Google Cloud
#       uses: google-github-actions/auth@v2
#       with:
#         credentials_json: '${{ secrets.GCP_SA_KEY }}'

#     - name: Deploy to Cloud Run
#       uses: google-github-actions/deploy-cloudrun@v2
#       with:
#         service: springboot-service
#         region: asia-south1
#         project_id: divine-quest-459017-j2
#         image: docker.io/${{ secrets.DOCKER_USERNAME }}/springboot-app
#         env_vars: |
#           SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#           SERVER_PORT=8080
